DROP TABLE IF EXISTS "user","token","connection";
CREATE TABLE IF NOT EXISTS "user"(
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "email" CHARACTER VARYING(255) NOT NULL,
  "password" CHARACTER VARYING(60) NOT NULL,
  "is_activated" BOOLEAN NOT NULL DEFAULT FALSE,
  "activation_link" CHARACTER VARYING(255) NOT NULL,
  "created_at" TIMESTAMP(3) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP(3)::TIMESTAMP,
  "online_at" TIMESTAMP(3) WITHOUT TIME ZONE
);
CREATE TABLE IF NOT EXISTS "token"(
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "id_user" BIGINT NOT NULL REFERENCES "user"("id"),
  "device_id" TEXT NOT NULL,
  "refresh_token" TEXT NOT NULL,
  "access_token" TEXT NOT NULL,
  "expires" TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL,
  "location" CHARACTER VARYING (255)
);
CREATE TABLE IF NOT EXISTS "connection"(
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "id_token" BIGINT NOT NULL REFERENCES "token"("id"),
  "peer" CHARACTER VARYING(36) NOT NULL
);
CREATE TABLE IF NOT EXISTS "image"(
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "title" CHARACTER VARYING(500) NOT NULL,
  "x64" CHARACTER VARYING(2000) NOT NULL,
  "x512" CHARACTER VARYING(2000) NOT NULL,
  "x1080" CHARACTER VARYING(2000) NOT NULL,
  "original" CHARACTER VARYING(2000) NOT NULL
);
CREATE TABLE IF NOT EXISTS "file"(
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "title" CHARACTER VARYING(500) NOT NULL,
  "path" CHARACTER VARYING(2000) NOT NULL
);
SELECT * FROM "token";
SELECT * FROM "connection";
SELECT * FROM "user";
